// <auto-generated />
using System;
using Logistica.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Logistica.Infrastructure.Migrations
{
    [DbContext(typeof(LogisticaDbContext))]
    partial class LogisticaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Logistica.Application.PaquetesRecibidos.PaqueteRecibido", b =>
                {
                    b.Property<Guid>("PaqueteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paquete_id");

                    b.Property<Guid>("ContratoCateringId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_catering_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaEntrega")
                        .HasColumnType("date")
                        .HasColumnName("fecha_entrega");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<string>("PacienteNombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paciente_nombre");

                    b.HasKey("PaqueteId");

                    b.HasIndex("FechaEntrega", "Estado")
                        .HasDatabaseName("IX_paquetes_recibidos_fecha_entrega_estado");

                    b.ToTable("paquetes_recibidos", (string)null);
                });

            modelBuilder.Entity("Logistica.Domain.Repartidores.Repartidor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Disponible")
                        .HasColumnType("boolean")
                        .HasColumnName("disponible");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.ToTable("repartidores", (string)null);
                });

            modelBuilder.Entity("Logistica.Domain.Rutas.ParadaEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ContratoCateringId")
                        .HasColumnType("uuid")
                        .HasColumnName("contrato_catering_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<int>("Orden")
                        .HasColumnType("integer")
                        .HasColumnName("orden");

                    b.Property<Guid>("PacienteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paciente_id");

                    b.Property<string>("PacienteNombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paciente_nombre");

                    b.Property<Guid>("PaqueteId")
                        .HasColumnType("uuid")
                        .HasColumnName("paquete_id");

                    b.Property<Guid>("RutaId")
                        .HasColumnType("uuid")
                        .HasColumnName("ruta_id");

                    b.HasKey("Id");

                    b.HasIndex("RutaId");

                    b.ToTable("paradas_entrega", null, t =>
                        {
                            t.HasCheckConstraint("CK_paradas_entrega_constancia_incidencia_excluyentes", "NOT (constancia_tipo IS NOT NULL AND incidencia_motivo IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Logistica.Domain.Rutas.RutaEntrega", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("DistanciaTotalKm")
                        .HasColumnType("numeric")
                        .HasColumnName("distancia_total_km");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<Guid>("RepartidorId")
                        .HasColumnType("uuid")
                        .HasColumnName("repartidor_id");

                    b.Property<int>("TiempoEstimadoMin")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_estimado_min");

                    b.Property<bool>("_optimizada")
                        .HasColumnType("boolean")
                        .HasColumnName("optimizada");

                    b.HasKey("Id");

                    b.HasIndex("Fecha")
                        .HasDatabaseName("IX_rutas_fecha");

                    b.HasIndex("RepartidorId")
                        .IsUnique()
                        .HasDatabaseName("UX_rutas_repartidor_activa")
                        .HasFilter("estado IN ('PENDIENTE','EN_CAMINO')");

                    b.ToTable("rutas", (string)null);
                });

            modelBuilder.Entity("Logistica.Application.PaquetesRecibidos.PaqueteRecibido", b =>
                {
                    b.OwnsOne("Logistica.Application.PaquetesRecibidos.EtiquetaPaquete", "Etiqueta", b1 =>
                        {
                            b1.Property<Guid>("PaqueteRecibidoPaqueteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CodigoQR")
                                .HasColumnType("text")
                                .HasColumnName("etiqueta_codigo_qr");

                            b1.Property<DateOnly>("Fecha")
                                .HasColumnType("date")
                                .HasColumnName("etiqueta_fecha");

                            b1.Property<string>("NombrePaciente")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("etiqueta_nombre_paciente");

                            b1.Property<string>("NroIdentificacion")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("etiqueta_nro_identificacion");

                            b1.Property<Guid>("PaqueteId")
                                .HasColumnType("uuid")
                                .HasColumnName("etiqueta_paquete_id");

                            b1.HasKey("PaqueteRecibidoPaqueteId");

                            b1.ToTable("paquetes_recibidos");

                            b1.WithOwner()
                                .HasForeignKey("PaqueteRecibidoPaqueteId");

                            b1.OwnsOne("Logistica.Domain.Shared.DireccionGeo", "DireccionEntrega", b2 =>
                                {
                                    b2.Property<Guid>("EtiquetaPaquetePaqueteRecibidoPaqueteId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Calle")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("etiqueta_direccion_calle");

                                    b2.Property<string>("Ciudad")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("etiqueta_direccion_ciudad");

                                    b2.Property<string>("Referencia")
                                        .HasColumnType("text")
                                        .HasColumnName("etiqueta_direccion_referencia");

                                    b2.Property<string>("Zona")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("etiqueta_direccion_zona");

                                    b2.HasKey("EtiquetaPaquetePaqueteRecibidoPaqueteId");

                                    b2.ToTable("paquetes_recibidos");

                                    b2.WithOwner()
                                        .HasForeignKey("EtiquetaPaquetePaqueteRecibidoPaqueteId");

                                    b2.OwnsOne("Logistica.Domain.Shared.Coordenadas", "Coordenadas", b3 =>
                                        {
                                            b3.Property<Guid>("DireccionGeoEtiquetaPaquetePaqueteRecibidoPaqueteId")
                                                .HasColumnType("uuid");

                                            b3.Property<decimal>("Latitud")
                                                .HasColumnType("numeric")
                                                .HasColumnName("etiqueta_direccion_latitud");

                                            b3.Property<decimal>("Longitud")
                                                .HasColumnType("numeric")
                                                .HasColumnName("etiqueta_direccion_longitud");

                                            b3.HasKey("DireccionGeoEtiquetaPaquetePaqueteRecibidoPaqueteId");

                                            b3.ToTable("paquetes_recibidos");

                                            b3.WithOwner()
                                                .HasForeignKey("DireccionGeoEtiquetaPaquetePaqueteRecibidoPaqueteId");
                                        });

                                    b2.Navigation("Coordenadas")
                                        .IsRequired();
                                });

                            b1.Navigation("DireccionEntrega")
                                .IsRequired();
                        });

                    b.OwnsOne("Logistica.Domain.Shared.DireccionGeo", "DireccionEntrega", b1 =>
                        {
                            b1.Property<Guid>("PaqueteRecibidoPaqueteId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("direccion_calle");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("direccion_ciudad");

                            b1.Property<string>("Referencia")
                                .HasColumnType("text")
                                .HasColumnName("direccion_referencia");

                            b1.Property<string>("Zona")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("direccion_zona");

                            b1.HasKey("PaqueteRecibidoPaqueteId");

                            b1.ToTable("paquetes_recibidos");

                            b1.WithOwner()
                                .HasForeignKey("PaqueteRecibidoPaqueteId");

                            b1.OwnsOne("Logistica.Domain.Shared.Coordenadas", "Coordenadas", b2 =>
                                {
                                    b2.Property<Guid>("DireccionGeoPaqueteRecibidoPaqueteId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Latitud")
                                        .HasColumnType("numeric")
                                        .HasColumnName("direccion_latitud");

                                    b2.Property<decimal>("Longitud")
                                        .HasColumnType("numeric")
                                        .HasColumnName("direccion_longitud");

                                    b2.HasKey("DireccionGeoPaqueteRecibidoPaqueteId");

                                    b2.ToTable("paquetes_recibidos");

                                    b2.WithOwner()
                                        .HasForeignKey("DireccionGeoPaqueteRecibidoPaqueteId");
                                });

                            b1.Navigation("Coordenadas")
                                .IsRequired();
                        });

                    b.Navigation("DireccionEntrega")
                        .IsRequired();

                    b.Navigation("Etiqueta")
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Domain.Repartidores.Repartidor", b =>
                {
                    b.OwnsOne("Logistica.Domain.Shared.Vehiculo", "Vehiculo", b1 =>
                        {
                            b1.Property<Guid>("RepartidorId")
                                .HasColumnType("uuid");

                            b1.Property<int>("CapacidadPaquetes")
                                .HasColumnType("integer")
                                .HasColumnName("vehiculo_capacidad_paquetes");

                            b1.Property<string>("Placa")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vehiculo_placa");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("vehiculo_tipo");

                            b1.HasKey("RepartidorId");

                            b1.ToTable("repartidores");

                            b1.WithOwner()
                                .HasForeignKey("RepartidorId");
                        });

                    b.Navigation("Vehiculo")
                        .IsRequired();
                });

            modelBuilder.Entity("Logistica.Domain.Rutas.ParadaEntrega", b =>
                {
                    b.HasOne("Logistica.Domain.Rutas.RutaEntrega", null)
                        .WithMany("_paradas")
                        .HasForeignKey("RutaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Logistica.Domain.Shared.DireccionGeo", "DireccionEntrega", b1 =>
                        {
                            b1.Property<Guid>("ParadaEntregaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Calle")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("direccion_calle");

                            b1.Property<string>("Ciudad")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("direccion_ciudad");

                            b1.Property<string>("Referencia")
                                .HasColumnType("text")
                                .HasColumnName("direccion_referencia");

                            b1.Property<string>("Zona")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("direccion_zona");

                            b1.HasKey("ParadaEntregaId");

                            b1.ToTable("paradas_entrega");

                            b1.WithOwner()
                                .HasForeignKey("ParadaEntregaId");

                            b1.OwnsOne("Logistica.Domain.Shared.Coordenadas", "Coordenadas", b2 =>
                                {
                                    b2.Property<Guid>("DireccionGeoParadaEntregaId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Latitud")
                                        .HasColumnType("numeric")
                                        .HasColumnName("direccion_latitud");

                                    b2.Property<decimal>("Longitud")
                                        .HasColumnType("numeric")
                                        .HasColumnName("direccion_longitud");

                                    b2.HasKey("DireccionGeoParadaEntregaId");

                                    b2.ToTable("paradas_entrega");

                                    b2.WithOwner()
                                        .HasForeignKey("DireccionGeoParadaEntregaId");
                                });

                            b1.Navigation("Coordenadas")
                                .IsRequired();
                        });

                    b.OwnsOne("Logistica.Domain.Shared.ConstanciaEntrega", "Constancia", b1 =>
                        {
                            b1.Property<Guid>("ParadaEntregaId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("FechaHora")
                                .HasColumnType("timestamptz")
                                .HasColumnName("constancia_fecha_hora");

                            b1.Property<string>("ReceptorNombre")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("constancia_receptor_nombre");

                            b1.Property<string>("Tipo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("constancia_tipo");

                            b1.Property<string>("UrlEvidencia")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("constancia_url_evidencia");

                            b1.HasKey("ParadaEntregaId");

                            b1.ToTable("paradas_entrega");

                            b1.WithOwner()
                                .HasForeignKey("ParadaEntregaId");

                            b1.OwnsOne("Logistica.Domain.Shared.Coordenadas", "CoordenadasConfirmacion", b2 =>
                                {
                                    b2.Property<Guid>("ConstanciaEntregaParadaEntregaId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Latitud")
                                        .HasColumnType("numeric")
                                        .HasColumnName("constancia_confirmacion_latitud");

                                    b2.Property<decimal>("Longitud")
                                        .HasColumnType("numeric")
                                        .HasColumnName("constancia_confirmacion_longitud");

                                    b2.HasKey("ConstanciaEntregaParadaEntregaId");

                                    b2.ToTable("paradas_entrega");

                                    b2.WithOwner()
                                        .HasForeignKey("ConstanciaEntregaParadaEntregaId");
                                });

                            b1.Navigation("CoordenadasConfirmacion");
                        });

                    b.OwnsOne("Logistica.Domain.Shared.IncidenciaEntrega", "Incidencia", b1 =>
                        {
                            b1.Property<Guid>("ParadaEntregaId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Descripcion")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("incidencia_descripcion");

                            b1.Property<DateTime>("FechaHora")
                                .HasColumnType("timestamptz")
                                .HasColumnName("incidencia_fecha_hora");

                            b1.Property<string>("Motivo")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("incidencia_motivo");

                            b1.Property<string>("UrlFoto")
                                .HasColumnType("text")
                                .HasColumnName("incidencia_url_foto");

                            b1.HasKey("ParadaEntregaId");

                            b1.ToTable("paradas_entrega");

                            b1.WithOwner()
                                .HasForeignKey("ParadaEntregaId");
                        });

                    b.Navigation("Constancia");

                    b.Navigation("DireccionEntrega")
                        .IsRequired();

                    b.Navigation("Incidencia");
                });

            modelBuilder.Entity("Logistica.Domain.Rutas.RutaEntrega", b =>
                {
                    b.Navigation("_paradas");
                });
#pragma warning restore 612, 618
        }
    }
}
